In [1]:
import numpy as np

Task 1

In [25]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [26]:
mean_a = np.array([np.mean(a[:, 0]), np.mean(a[:, 1])])
mean_a

array([2. , 8.4])

Task 2

In [29]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Task 3

In [31]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp/4

2.0

Task 4

In [33]:
np.cov(a.T)[0, 1]

2.0